@hostName = http://localhost
@hostPort = 3002
### Simple api
GET {{hostName}}:{{hostPort}}/hello

### Create new user
POST {{hostName}}:{{hostPort}}/user
Content-Type: application/json

{
    "name": "khang",
    "email": "khang17@gmail.com",
    "password": "1234",
    "address": "Nghe An"
}

### Get all users
GET {{hostName}}:{{hostPort}}/user

### Get user by id
GET {{hostName}}:{{hostPort}}/user/1

### Update user by id
PUT {{hostName}}:{{hostPort}}/user/1
Content-Type: application/json

{
    "name": "khang",
    "email": "khanghoangvan29042003@gmail.com",
    "address": "Nghe An"
}

### Delete user by id
DELETE {{hostName}}:{{hostPort}}/user/1