// Environment definition
@hostName = http://localhost
@hostPort = 3002

@jwtADMINToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0MjM2Mjg1NywiZXhwIjoxNzQyNDQ5MjU3fQ.f19SwqcvDK8GroDkyI-HwYvjIVaMAym2b47Cvp_enns

@jwtUSERToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzQyMzYzMTA3LCJleHAiOjE3NDI0NDk1MDd9.cge4QRtBQB70dj7CX1sBTdjTeyqymT8H0y-LzJtWGuE


# @jwtToken = {{jwtUSERToken}}
@jwtToken = {{jwtUSERToken}}


########################################################################
########################################################################

// LOGIN - SIGNUP

### Signup
POST {{hostName}}:{{hostPort}}/auth/signup
Content-Type: application/json

{
    "name": "admin",
    "email": "admin17@gmail.com",
    "password": "admin",
    "address": "Nghe An"
}

### Login admin account
POST {{hostName}}:{{hostPort}}/auth/login
Content-Type: application/json

{
    "email": "admin17@gmail.com",
    "password": "admin"
}


### Login user account
POST {{hostName}}:{{hostPort}}/auth/login
Content-Type: application/json

{
    "email": "khanghv17@gmail.com",
    "password": "1234"
}


#######################################################################
#######################################################################

// CRUD --- USER

###
GET {{hostName}}:{{hostPort}}/user
Authorization: {{jwtToken}}

###
GET {{hostName}}:{{hostPort}}/user/2
Authorization: {{jwtToken}}








#######################################################################
#######################################################################

// CRUD --- PROFILE


### Create Profile
POST {{hostName}}:{{hostPort}}/profile
Authorization: {{jwtToken}}
Content-Type: application/json

{
    "bio": "hellohellohello",
    "avatar": "chua co nha"
}

### get Profile
GET {{hostName}}:{{hostPort}}/profile
Authorization: {{jwtToken}}

### Update profile
PATCH {{hostName}}:{{hostPort}}/profile
Authorization: {{jwtToken}}
Content-Type: application/json

{
    "bio": "papapa",
    "avatar": "chua co nha"
}

### Delete profile
DELETE {{hostName}}:{{hostPort}}/profile
Authorization: {{jwtToken}}














#######################################################################
#######################################################################

// CRUD --- POST


### Create post
POST {{hostName}}:{{hostPort}}/post 
Authorization: {{jwtToken}}
Content-Type: application/json

{
    "title": "admin",
    "content": "nestjs, prisma, postgresql, jwt, passport, guard, module, import, export, controller, provider"
}

### Get all post
GET {{hostName}}:{{hostPort}}/post
Authorization: {{jwtToken}}

### Get post
GET {{hostName}}:{{hostPort}}/post/3
Authorization: {{jwtToken}}

### Update post
PATCH {{hostName}}:{{hostPort}}/post/3
Authorization: {{jwtToken}}
Content-Type: application/json

{
    "title": "yootek intern update",
    "content": "updated content: nestjs with something else"
}

### Delete post 
DELETE {{hostName}}:{{hostPort}}/post/8
Authorization: {{jwtToken}}









